name: Angular CI

env:
  playstore_name: QlockToo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          cd qlocktoo-portal
          npm i
          npm run build:prod
          npx cap sync
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: qlocktoo-portal/dist
          retention-days: 1
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      # Create APK Release
      - name: Build apk release project (APK)
        run: |
          cd qlocktoo-portal/android
          ./gradlew assemble

      # Noted For Output [qlocktoo-portal]/build/outputs/apk/release/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
          path: qlocktoo-portal/android/app/build/outputs/apk/release/