name: Angular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          cd qlocktoo-portal
          npm i
          npm run build:prod
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: qlocktoo-portal/dist
          retention-days: 1